### ISSUE TITLE
Change validator management design

### ISSUE THREAD

**Issue by RadoslavDimchev** [status-im/nimbus-gui#121]
We have some new changes from Figma for this screen, add border for table, improve tabs with icon and validators amount, make tabs in one row with search bar and make search bar with the length of search icon, which changes the width after click.
New design:
![image](https://github.com/status-im/nimbus-gui/assets/101931596/3941f176-8b06-400f-91ff-805a75de0893)
Current design:
![image](https://github.com/status-im/nimbus-gui/assets/101931596/61c85e92-75f2-4466-8952-c0617d1ce51b)

**Comment by EmilIvanichkovv** [comment]
https://github.com/status-im/nimbus-gui/issues/130
