### ISSUE TITLE
[Currency Dropdown] -> Add currency symbol

### ISSUE THREAD

**Issue by RadoslavDimchev** [status-im/nimbus-gui#139]
After already we have real currencies, it will be better to show the symbol also. 
![image](https://github.com/status-im/nimbus-gui/assets/101931596/5c37e9d6-9733-4ff2-b16d-a8ce3fd6ef36)

**Comment by EmilIvanichkovv** [comment]
Done with https://github.com/status-im/nimbus-gui/commit/ab8a571668e32aba6913b0630655b408f05b9a6b
