### ISSUE TITLE
Investigate and integrate charts library for components

### ISSUE THREAD

**Issue by GoNZooo** [status-im/nimbus-gui#6]
A charts & graphs library should be integrated into the project in order to reliably produce the types of graphs, gauges and charts that are in use on the dashboard pages and the like.

**Comment by HristoNedelkov** [comment]
As described in the Nimbus • Project Rainfall 360°

I think we must use:
https://www.notion.so/Charts-Implementation-6ad2b8a95c14482d8730c77c5a8eda66?p=88f791482c05451c8952ba4bb0311aa2&pm=s

**Comment by GoNZooo** [comment]
This was solved, as far as we know, in #17
