### ISSUE TITLE
Create dashboard

### ISSUE THREAD

**Issue by RadoslavDimchev** [status-im/nimbus-gui#67]

**Comment by HristoNedelkov** [comment]
It offers a wide range of options for customizations, which would enable us to tailor the charts as per our design specifications.
Alignment with Design Goals: Based on the current analysis, it appears that utilizing Chart.js (https://www.chartjs.org/) will help us achieve a visual representation that aligns closest to our planned design.
However, I have encountered a hurdle - as of now, I haven't found a direct method within the library to filter and display data over a specific period.
 I plan to extend my research and explore possible solutions or workarounds for this.

I am optimistic about finding a solution shortly, post which I will make an informed decision on whether to proceed with Chart.js for developing the line chart in our dashboard.

I welcome any suggestions or insights that might help in overcoming this challenge.
