### ISSUE TITLE
Create dashboard grid

### ISSUE THREAD

**Issue by RadoslavDimchev** [status-im/nimbus-gui#72]
Resources from Aqeel:
- https://betterprogramming.pub/build-a-responsive-modern-dashboard-layout-with-css-grid-and-flexbox-bd343776a97e
- https://codepen.io/trooperandz/pen/YRpKjo
- https://codepen.io/trooperandz/pen/EOgJvg

**Comment by HristoNedelkov** [comment]
Could someone with the appropriate permissions please close this issue as the associated PR has been merged? Thank you!
