### ISSUE TITLE
Create standard gauge component as used for "Storage" on "Device Health Check" screen

### ISSUE THREAD

**Issue by GoNZooo** [status-im/nimbus-gui#8]
The "Device Health Check" page has a gauge that shows the currently used storage. This component should be created so that it can be reused on multiple pages. Note that several variants of this exist and have multiple layers being used for showing sub-types of storage (see "Validator Management" page where "Storage" is shown in more detail)

**Comment by HristoNedelkov** [comment]
Closed by #17
